apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: workshopcolorservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: workshopcolorservice
    spec:
      containers:
      - name: workshopcolorservice
        image: pblaas/workshop_colorservice:initial
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
        ports:
        - containerPort: 80
