kind: Service
apiVersion: v1
metadata:
  name: workshop-colorservice
  labels:
    tier: demoapp
spec:
  selector:
    app: workshopcolorservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
